
[package]
authors.workspace = true
description = "A package management and workflow tool"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "pixi_api"
readme.workspace = true
repository.workspace = true
version = "0.50.1"

[features]
default = ["online_tests", "rustls-tls"]
native-tls = [
    "reqwest/native-tls",
    "reqwest/native-tls-alpn",
    "rattler_repodata_gateway/native-tls",
    "rattler/native-tls",
    "pixi_utils/native-tls",
]
# run tests connecting to remote Internet services
online_tests = []
rustls-tls = [
    "reqwest/rustls-tls",
    "reqwest/rustls-tls-native-roots",
    "rattler_repodata_gateway/rustls-tls",
    "rattler/rustls-tls",
    "pixi_utils/rustls-tls",
]
self_update = []
slow_integration_tests = []
tokio-console = ["console-subscriber", "tokio/tracing"]

# This feature enables performance optimizations but at the cost of increased
# compile times. By default, it is only used when building the release binary.
performance = ["pixi_allocator"]

[dependencies]
ahash = { workspace = true }
assert_matches = { workspace = true }
async-once-cell = { workspace = true }
barrier_cell = { path = "./../barrier_cell" }
chrono = { workspace = true }
clap = { workspace = true, features = [
    "derive",
    "usage",
    "wrap_help",
    "std",
    "color",
    "error-context",
    "env",
] }
clap_complete = { workspace = true }
clap_complete_nushell = { workspace = true }
console = { workspace = true, features = ["windows-console-colors"] }
console-subscriber = { workspace = true, optional = true }
crossbeam-channel = { workspace = true }
csv = { workspace = true }
dashmap = { workspace = true }
deno_task_shell = { workspace = true }
dialoguer = { workspace = true }
dirs = { workspace = true }
dunce = { workspace = true }
fancy_display = { workspace = true }
flate2 = { workspace = true }
fs_extra = { workspace = true }
futures = { workspace = true }
human_bytes = { workspace = true }
humantime = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
indicatif = { workspace = true }
is_executable = { workspace = true }
itertools = { workspace = true }
miette = { workspace = true, features = ["fancy-no-backtrace"] }
minijinja = { workspace = true, features = ["builtins"] }
once_cell = { workspace = true }
parking_lot = { workspace = true }
pathdiff = { workspace = true }
rstest = { workspace = true }
uv-build-frontend = { workspace = true }
uv-distribution-filename = { workspace = true }
uv-distribution-types = { workspace = true }
uv-install-wheel = { workspace = true }

pep440_rs = { workspace = true }
pep508_rs = { workspace = true }
percent-encoding = { workspace = true }
rattler = { workspace = true, features = ["cli-tools", "indicatif"] }
rattler_conda_types = { workspace = true }
rattler_digest = { workspace = true }
rattler_lock = { workspace = true }
rattler_menuinst = { workspace = true }
rattler_networking = { workspace = true }
rattler_repodata_gateway = { workspace = true, features = [
    "sparse",
    "gateway",
] }
rattler_shell = { workspace = true, features = ["sysinfo"] }
rattler_solve = { workspace = true, features = ["resolvo", "serde"] }
uv-git = { workspace = true }
uv-pep440 = { workspace = true }
uv-pep508 = { workspace = true }
uv-pypi-types = { workspace = true }

anyhow = "1.0.97"
ctrlc = { workspace = true }
fs-err = { workspace = true, features = ["tokio"] }
pixi_allocator = { workspace = true, optional = true }
pixi_build_discovery = { workspace = true }
pixi_build_frontend = { workspace = true }
pixi_build_type_conversions = { workspace = true }
pixi_command_dispatcher = { workspace = true }
pixi_config = { workspace = true }
pixi_consts = { workspace = true }
pixi_default_versions = { workspace = true }
pixi_git = { workspace = true }
pixi_glob = { workspace = true }
pixi_manifest = { workspace = true, features = ["rattler_lock"] }
pixi_progress = { workspace = true }
pixi_pypi_spec = { workspace = true }
pixi_record = { workspace = true }
pixi_spec = { workspace = true }
pixi_spec_containers = { workspace = true }
pixi_toml = { workspace = true }
pixi_utils = { workspace = true, default-features = false }
pixi_uv_conversions = { workspace = true }
pypi_mapping = { workspace = true }
pypi_modifiers = { workspace = true }
rattler_virtual_packages = { workspace = true }
rayon = "1.10.0"
regex = { workspace = true }
reqwest = { workspace = true, features = [
    "http2",
    "macos-system-configuration",
] }
reqwest-middleware = { workspace = true }
rlimit = { workspace = true }
self-replace = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true, features = ["indexmap"] }
shlex = { workspace = true }
strsim = { workspace = true }
tabwriter = { workspace = true, features = ["ansi_formatting"] }
tar = { workspace = true }
temp-env = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tokio-util = { workspace = true }
toml-span = { workspace = true }
toml_edit = { workspace = true, features = ["serde"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
typed-path = { workspace = true }
url = { workspace = true }
uv-auth = { workspace = true }
uv-cache = { workspace = true }
uv-cache-info = { workspace = true }
uv-client = { workspace = true }
uv-configuration = { workspace = true }
uv-dispatch = { workspace = true }
uv-distribution = { workspace = true }
uv-git-types = { workspace = true }
uv-installer = { workspace = true }
uv-normalize = { workspace = true }
uv-python = { workspace = true }
uv-redacted = { workspace = true }
uv-requirements = { workspace = true }
uv-requirements-txt = { workspace = true }
uv-resolver = { workspace = true }
uv-types = { workspace = true }
uv-workspace = { workspace = true }
xxhash-rust = { workspace = true }
zip = { workspace = true, features = ["deflate", "time"] }
zstd = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true, default-features = false }
nix = { workspace = true, features = ["poll", "term"] }
pixi_pty = { path = "./../pixi_pty" }
sha2 = { workspace = true, features = ["asm"] }
signal-hook = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
fake = "4.0.0"
http = { workspace = true }
insta = { workspace = true, features = ["yaml", "glob", "filters"] }
pixi_test_utils = { workspace = true }
rstest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
